apiBaseUrl=http://localhost:4111
apiVersion=/api/v1
adminLogin=admin
adminPassword=admin
adminToken=Basic YWRtaW46YWRtaW4=

#UI
uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://192.168.1.99:3000
uiBrowser = chrome
uiBrowserSize = 1920x1080

#Test
TestScope=smoke