adminLogin=admin
adminPassword=admin
adminToken=Basic YWRtaW46YWRtaW4=

#UI
uiRemote = http://localhost:4444/wd/hub
uiBaseUrl = http://192.168.1.143:3000
uiBrowser = chrome
uiBrowserSize = 1920x1080

#Test
TestScope=smoke

#DB (адрес хранилища задан в api.configs.BackendVersion — он версионный)
db.username=postgres
db.password=postgres
