# Format: RequestClass=ResponseClass:field1=field1Response,field2=fields2Response

CreateUserRequest=CreateUserResponse:username=username,role=role
DepositMoneyRequest=DepositMoneyResponse:id=id
TransferMoneyRequest=TransferMoneyResponse:senderAccountId=senderAccountId,receiverAccountId=receiverAccountId,amount=amount
ChangeNameRequest=ChangeNameResponse:name=customer.name
